### ISSUE TITLE
【提问】能否自己更新device.ts

### ISSUE THREAD

**Issue by CatOverrun** [icqqjs/icqq#102]
1. 使用场景是直接用的Miao-Yunzai 里的package.json，通过pnpm安装的icqq，并非为自己的项目。
2. - icqq版本为0.4.11时，当前aPad协议版本为8.9.68
    - 2023年7月20日时，[qsign签名项](https://github.com/fuqiuluo/unidbg-fetch-qsign)和对应的[protocol项目](https://github.com/mikko-mikust/protocol-versions)已更新8.9.70协议。
3. 同时还有cq等其他端，依赖于qsign签名。

目前解决办法是开两个qsign一个8.9.68，一个8.9.70，然后等待icqq更新。

注意到在[./node_modules/.pnpm/icqq@0.4.11/node_modules/icqq/lib/core/device.js](https://github.com/icqqjs/icqq/blob/main/src/core/device.ts)内有和协议相关的内容。但由于格式和编码似乎和上文提到的protocol项目不同，需要转换得来。

对比如下：
icqq内的8.9.68:
```yaml
{
    id: "com.tencent.mobileqq",
    app_key: '0S200MNJT807V3GE',
    name: "A8.9.68.11565",
    version: "8.9.68.11565",
    ver: "8.9.68",
    sign: Buffer.from('A6 B7 45 BF 24 A2 C2 77 52 77 16 F6 F3 6E B6 8D'.split(' ').map(s => parseInt(s, 16))),
    buildtime: 1687254022,
    appid: 16,
    subid: 537168313,
    bitmap: 150470524,
    main_sig_map: 16724722,
    sub_sig_map: 0x10400,
    sdkver: "6.0.0.2549",
    display: "Android",
    qua: 'V1_AND_SQ_8.9.68_4264_YYB_D',
    ssover: 20,
}
```
如使用aPad则:
```yaml
{
    subid: 537168361,
    display: 'aPad',
}
```
version-protocol中的8.9.68 aPad协议json:
```json
{
    "apk_id": "com.tencent.mobileqq",
    "app_id": 537168361,
    "sub_app_id": 537168361,
    "app_key": "0S200MNJT807V3GE",
    "sort_version_name": "8.9.68.11565",
    "build_time": 1688523354,
    "apk_sign": "7772804f3cb4961f57cb764fbe4973e6",
    "sdk_version": "6.0.0.2549",
    "sso_version": 20,
    "misc_bitmap": 150470524,
    "main_sig_map": 34869472,
    "sub_sig_map": 66560,
    "dump_time": 1689780543,
    "qua": "V1_AND_SQ_8.9.68_4264_YYB_D",
    "protocol_type": 6
}
```
version-protocol中的8.9.70 aPad协议json:
```json
{
    "apk_id": "com.tencent.mobileqq",
    "app_id": 537169425,
    "sub_app_id": 537169425,
    "app_key": "0S200MNJT807V3GE",
    "sort_version_name": "8.9.70.11635",
    "build_time": 1689572864,
    "apk_sign": "c67b3780e3a04a0de773115beafebb42",
    "sdk_version": "6.0.0.2551",
    "sso_version": 20,
    "misc_bitmap": 150470524,
    "main_sig_map": 34869472,
    "sub_sig_map": 66560,
    "dump_time": 1689651775,
    "qua": "V1_AND_SQ_8.9.70_4292_HDBM_T",
    "protocol_type": 6
}
```
对node.js实在是不太了解
不知道这种通过pnpm安装的icqq，直接仅修改device.ts 能否有效。
不知道如何通过version-protocol给的协议json转换成icqq里用的格式。
