### ISSUE TITLE
未配置签名API地址，登录/消息发送可能失败

### ISSUE THREAD

**Issue by linonetwo** [icqqjs/icqq#78]
### Node.js Version

v20.2.0

### Package(icqq) Version

0.4.7

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

如何配置签名API地址？这个或许能解决报错 45 的问题？

### Log Details (控制台日志，请提供包含前后一段时间内的)

未配置签名API地址，登录/消息发送可能失败

xxx

[2023-06-27T14:40:48.744] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联
系。(错误码：45)
[2023-06-27T14:40:48.745] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

**Comment by Yizelove** [comment]
sign_api_addr: http://qi.yize.site/sign
把这个添加到bot.yaml文件最下方
然后联系2033390600过白机器人QQ

**Comment by lc-cn** [comment]
```yaml
adapters:
  bots:
    - self_id: '' # 你的id
      sign_api_addr: '' # 签名地址
```
参考上边的接口

**Comment by Yizelove** [comment]
> <img alt="屏幕截图 2023-07-03 152921" width="926" src="https://user-images.githubusercontent.com/3746270/250488129-0de7bbaf-e2cf-470f-bca3-20bcd2e8e915.png">
> zhin 侧配置成功了，现在可以看到报错
> 
> [ERROR] [icqq] - 签名api异常： wtlogin.login result: "<script src="/_guard/auto.js"></script>"

已放行/_guard/auto.js，重新试试看

**Comment by linonetwo** [comment]
解决了，不过现在有新的报错了

签名api异常： wtlogin.login result: {"code":-1}

没有更详细的报错信息了

**Comment by Yizelove** [comment]
> 解决了，不过现在有新的报错了
> 
> 签名api异常： wtlogin.login result: {"code":-1}
> 
> 没有更详细的报错信息了

我也没办法了，Yunzai-Bot的都正常，不知道你为啥这样

**Comment by lc-cn** [comment]
> > 解决了，不过现在有新的报错了
> > 签名api异常： wtlogin.login result: {"code":-1}
> > 没有更详细的报错信息了
> 
> 我也没办法了，Yunzai-Bot的都正常，不知道你为啥这样


> 解决了，不过现在有新的报错了
> 
> 签名api异常： wtlogin.login result: {"code":-1}
> 
> 没有更详细的报错信息了

platform传6，大概率是因为这个API没有tim的签名

**Comment by linonetwo** [comment]
试了

```yml
port: 8086
adapters:
  icqq:
    bots:
      - self_id: 1xx
        platform: 1
        master: 5xx
        data_dir: data
        reconn_interval: 600
        password: Yn
        sign_api_addr: http://qi.yize.site/sign
```

或 platform: 2

并 `rm .\data\device.json`

也还是

[2023-07-03T15:42:16.629] [MARK] [icqq] - 创建了新的设备文件：D:\repo\qq-bot\data\device.json
[2023-07-03T15:42:16.630] [MARK] [icqq] - ----------
[2023-07-03T15:42:16.630] [MARK] [icqq] - Package Version: icqq@0.4.8 (Released on 2023/7/1)
[2023-07-03T15:42:16.630] [MARK] [icqq] - View Changelogs：https://github.com/icqqjs/icqq/releases
[2023-07-03T15:42:16.630] [MARK] [icqq] - ----------
[2023-07-03T15:42:16.631] [INFO] [icqq] - [1287688945]使用协议：Android_8.9.63.11390
[2023-07-03T15:42:17.259] [ERROR] [icqq] - 签名api异常： wtlogin.login result: {"code":-1}

[2023-07-03T15:42:02.736] [MARK] [icqq] - 创建了新的设备文件：D:\repo\qq-bot\data\device.json
[2023-07-03T15:42:02.736] [MARK] [icqq] - ----------
[2023-07-03T15:42:02.736] [MARK] [icqq] - Package Version: icqq@0.4.8 (Released on 2023/7/1)
[2023-07-03T15:42:02.736] [MARK] [icqq] - View Changelogs：https://github.com/icqqjs/icqq/releases
[2023-07-03T15:42:02.736] [MARK] [icqq] - ----------
[2023-07-03T15:42:02.737] [INFO] [icqq] - [1287688945]使用协议：aPad_8.9.63.11390
[2023-07-03T15:42:03.163] [ERROR] [icqq] - 签名api异常： wtlogin.login result: {"code":-1}
